language: python
python:
  - "3.4.5"
  - "3.5"
  - "3.6"
env:
  - CIRCLE_NODE_TOTAL=5 CIRCLE_NODE_INDEX=0
  - CIRCLE_NODE_TOTAL=5 CIRCLE_NODE_INDEX=1
  - CIRCLE_NODE_TOTAL=5 CIRCLE_NODE_INDEX=2
  - CIRCLE_NODE_TOTAL=5 CIRCLE_NODE_INDEX=3
  - CIRCLE_NODE_TOTAL=5 CIRCLE_NODE_INDEX=4
install:
  - "pip install ."
  - "pip install pytest hypothesis"
  - "pip install git+https://github.com/pybee/pytest-circleci"
  - "pip install flake8"
script:
  - flake8 && ant checkstyle && py.test tests
